name = "nuwavmedia1"
compatibility_date = "2025-08-04"

# Tell wrangler where the worker entrypoint is after build
main = ".vercel/output/static/_worker.js"

[build]
command = "npm install && npm run build"
